apiVersion: v1

kind: Pod

metadata:

  creationTimestamp: null

  labels:

    run: webapptest

  name: webapptest

spec:

  containers:

  - image: msakhil7/samplewebapp

    command: ["sleep", "1000"]

    name: test

    resources: {}

  dnsPolicy: ClusterFirst

  restartPolicy: Always

status: {}

---

apiVersion: v1

kind: Service

metadata:

  creationTimestamp: null

  labels:

    run: webapptest

  name: webapptest

spec:

  ports:

  - port: 80

    protocol: TCP

    targetPort: 80

    nodePort: 30008

  selector:

    run: webapptest

  type: NodePort

status:

  loadBalancer: {}
